### ISSUE TITLE
Error following the debian install guide

### ISSUE THREAD

**Issue by glimow** [cozy/cozy-stack#1820]
I followed the debian install guide (https://docs.cozy.io/en/tutorials/selfhost-debian/) on a debian sketch scaleway server, and got this error when running `cozy-coclyco create cozy.buenos-aires.fr tristan.kalos@live.fr`:
```
[INF] Issue certificate for {'home.cozy.buenos-aires.fr', 'photos.cozy.buenos-aires.fr', 'store.cozy.buenos-aires.fr', 'drive.cozy.buenos-aires.fr', 'cozy.buenos-aires.fr', 'settings.cozy.buenos-aires.fr'}
[INF] Validate home.cozy.buenos-aires.fr
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f94a708a748>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='home.cozy.buenos-aires.fr', port=80): Max retries exceeded with url: /.well-known/acme-challenge/PPFUFTds7uHZH3S5zabkNRhe81CJRP8ZtCT37dXT3Kc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f94a708a748>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cozy-coclyco", line 11, in <module>
    load_entry_point('cozy-coclyco==1.0', 'console_scripts', 'cozy-coclyco')()
  File "/usr/lib/python3/dist-packages/cozy/coclyco/__init__.py", line 56, in cli
    args.cmd(args)
  File "/usr/lib/python3/dist-packages/cozy/coclyco/pki.py", line 139, in create_instance
    self.__issue_certificate(slug, domain)
  File "/usr/lib/python3/dist-packages/cozy/coclyco/pki.py", line 94, in __issue_certificate
    self._issue_certificate(csr)
  File "/usr/lib/python3/dist-packages/cozy/coclyco/acme.py", line 264, in _issue_certificate
    auth = [self.__authorize_domain(domain) for domain in domains]
  File "/usr/lib/python3/dist-packages/cozy/coclyco/acme.py", line 264, in <listcomp>
    auth = [self.__authorize_domain(domain) for domain in domains]
  File "/usr/lib/python3/dist-packages/cozy/coclyco/acme.py", line 190, in __authorize_domain
    response = requests.get(url, verify=False)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='home.cozy.buenos-aires.fr', port=80): Max retries exceeded with url: /.well-known/acme-challenge/PPFUFTds7uHZH3S5zabkNRhe81CJRP8ZtCT37dXT3Kc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f94a708a748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

By the way, is there any documentation on how to install with a custom reverse-proxy ? I didn't find anything about the domain name configuration of sub services.

**Comment by nono** [comment]
Hello,

> By the way, is there any documentation on how to install with a custom reverse-proxy ?

@aeris do we have that?

> I didn't find anything about the domain name configuration of sub services.

It is documented on https://docs.cozy.io/en/tutorials/selfhost-debian/#dns.

**Comment by glimow** [comment]
Hello nono, 
thanks for the answer. 
I have taken a look at that link but unfortunately it does not give enough details about the virtual hosting configuration to use a custom reverse proxy. 
Any Idea about the error using default cozy-cloud config btw ?

**Comment by aeris** [comment]
> I have taken a look at that link but unfortunately it does not give enough details about the virtual hosting configuration to use a custom reverse proxy.

We don't support this deployment setup official because to much way to do that depending of your setup.

In short, you have to forward all traffic from `cozy.fqdn` and `*.cozy.fqdn` to the Cozy nginx.
Beware of websocket negociation (`Content` & `Upgrade` HTTP headers).

In this mode, you can't use `cozy-coclyco` too (which suppose certificates to be served by the Cozy nginx and not your reverse proxy) and so you create your instance manually (with `cozy-stack instance add` [like Coclyclo](https://github.com/cozy/cozy-coclyco/blob/master/cozy/coclyco/pki.py#L119)) then applications (with `cozy-stack apps install` [like Coclyco](https://github.com/cozy/cozy-coclyco/blob/master/cozy/coclyco/pki.py#L128-L134)) and must deploy manually certificates and Cozy nginx vhost (based on https://github.com/cozy/cozy-coclyco/blob/master/cozy/coclyco/nginx.conf for example).

But keep in mind this is an unsupported deployment setup and not really easy to achieve.

> Any Idea about the error using default cozy-cloud config btw ?

> [INF] Validate home.cozy.buenos-aires.fr
> socket.gaierror: [Errno -2] Name or service not known
Seems your DNS doesn't resolve the `home.cozy.buenos-aires.fr` FQDN
